require('keybindings')
require('plugins')
require('options')
require('lualine-config')
require('bufferline-config')
require('treesitter-config')
require('autopairs-config')
require('whichkey-config')
require('quickscope-config')
require('telescope-config')
require('lsp')
require('vimwiki-config')
vim.g.onedark_style = 'darker'
require('onedark').setup()
