-- return {
--     {
--       "folke/which-key.nvim",
--       event = "VeryLazy",
--       init = function()
--         vim.o.timeout = true
--         vim.o.timeoutlen = 0
--       end,
--     },
--     {
--         "kylechui/nvim-surround",
--         version = "*", -- Use for stability; omit to use `main` branch for the latest features
--         event = "VeryLazy",
--         config = function()
--             require("nvim-surround").setup()
--         end
--     },
--     {
--         "rcarriga/nvim-dap-ui",
--         dependencies = "mfussenegger/nvim-dap",
--     },
-- }
